### ISSUE TITLE
License

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/wkhtmltox#4]
I would assume that I can't use a PHP license for this extension ... can someone apply a suitable license please ?

I really don't care what license is used, it seems more important to @remicollet than anyone else ?

**Comment by remicollet** [comment]
As PHP License is mostly a BSD variant, whould be the simplest solution to use BSD.

> I really don't care what license is used, it seems more important to @remicollet than anyone else ?

I fact I only care about "free" license ;)
But indeed PHP License probably only make sense for project in php.net (and, AFAIK, debian don't like it, but Fedora don't care)

**Comment by krakjoe** [comment]
Seems reasonable to use a BSD license then, can you take care of changing it please ?

**Comment by remicollet** [comment]
@weltling is BSD ok for you ?

**Comment by weltling** [comment]
Yeah, i'm totally fine with BSD. If in doubt, FSF has also a legal department one could consult directly. Otherwise they list some https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses that they call explicitly compatible with GPL, consequently they should be compatible with LGPL. 

Thanks.
